export type Product = {
  id: string;
  name: string;
  category: string;
  unit: string;
  pricePerUnit: number;
  moq: number;
  origin: string;
  grade: string;
  lead: string;
  blurb: string;
  spec: string[];
};

export const PRODUCTS: Product[] = [
  {
    id: "sorghum-white",
    name: "White Sorghum",
    category: "Cereals",
    unit: "MT",
    pricePerUnit: 410,
    moq: 5,
    origin: "Kalobeyei Irrigation Cluster",
    grade: "Grade 1",
    lead: "7–10 days",
    blurb: "Drought-tolerant cereal aggregated from 400+ smallholder plots along the Tarach belt.",
    spec: ["Moisture ≤ 13%", "Foreign matter ≤ 1%", "Aflatoxin < 10 ppb", "50kg PP bags"],
  },
  {
    id: "green-grams",
    name: "Green Grams (Ndengu)",
    category: "Pulses",
    unit: "MT",
    pricePerUnit: 985,
    moq: 3,
    origin: "Lokichar Producer Group",
    grade: "Grade 1",
    lead: "10–14 days",
    blurb: "High-protein pulse with consistent sizing, machine-cleaned at the Kakuma grading yard.",
    spec: ["Moisture ≤ 12%", "Purity ≥ 99%", "Hand-sorted", "25kg / 50kg bags"],
  },
  {
    id: "cowpeas",
    name: "Cowpeas",
    category: "Pulses",
    unit: "MT",
    pricePerUnit: 760,
    moq: 3,
    origin: "Turkana West Cooperatives",
    grade: "Grade 2",
    lead: "10–14 days",
    blurb: "Dual-purpose legume supporting soil nitrogen fixation across climate-smart rotations.",
    spec: ["Moisture ≤ 13%", "Split ≤ 2%", "Fumigated", "50kg bags"],
  },
  {
    id: "sukuma-wiki",
    name: "Kale (Sukuma Wiki)",
    category: "Fresh Produce",
    unit: "Crate (20kg)",
    pricePerUnit: 14,
    moq: 40,
    origin: "Nadapal Solar Cold Hub",
    grade: "Fresh A",
    lead: "24–48 hrs",
    blurb: "Cold-chain leafy greens harvested at dawn and pre-cooled within four hours.",
    spec: ["Cold chain 2–6°C", "Field-washed", "Vented crates", "Same-day dispatch"],
  },
  {
    id: "tomatoes",
    name: "Field Tomatoes",
    category: "Fresh Produce",
    unit: "Crate (25kg)",
    pricePerUnit: 21,
    moq: 30,
    origin: "Napusimoru Riverine Farms",
    grade: "Fresh A",
    lead: "24–72 hrs",
    blurb: "Firm determinate varieties graded for institutional catering and retail packhouses.",
    spec: ["Uniform sizing", "Cold chain 8–12°C", "Ventilated crates", "Traceable lot codes"],
  },
  {
    id: "goat-meat",
    name: "Chilled Goat Carcass",
    category: "Livestock",
    unit: "Carcass (12kg avg)",
    pricePerUnit: 68,
    moq: 25,
    origin: "Turkana Pastoralist Network",
    grade: "Inspected",
    lead: "3–5 days",
    blurb: "Veterinary-inspected small stock sourced through mobile pastoralist aggregation points.",
    spec: ["Vet certificate", "Cold chain 0–4°C", "Halal slaughter", "Lot traceability"],
  },
  {
    id: "sesame",
    name: "Sesame Seed",
    category: "Oilseeds",
    unit: "MT",
    pricePerUnit: 1450,
    moq: 2,
    origin: "Kaikor Corridor",
    grade: "Export",
    lead: "14–21 days",
    blurb: "Export-grade whitish sesame consolidated for cross-border freight to Juba and Kampala.",
    spec: ["Oil content ≥ 48%", "Purity ≥ 99.5%", "Moisture ≤ 7%", "Export documentation"],
  },
  {
    id: "honey",
    name: "Raw Acacia Honey",
    category: "Specialty",
    unit: "Drum (25kg)",
    pricePerUnit: 165,
    moq: 8,
    origin: "Lopiding Apiary Collective",
    grade: "Grade A",
    lead: "7–12 days",
    blurb: "Single-origin acacia honey from arid-land apiaries managed by women-led collectives.",
    spec: ["Moisture ≤ 19%", "Unheated", "Food-grade drums", "Lab report included"],
  },
  {
    id: "onions",
    name: "Onions",
    category: "Fresh Produce",
    unit: "Bag (50kg)",
    pricePerUnit: 45,
    moq: 10,
    origin: "Turkana Fresh Markets",
    grade: "Fresh A",
    lead: "3–5 days",
    blurb: "Fresh, quality onions sourced from local farmers and aggregation points.",
    spec: ["Fresh grade", "50kg bags", "Field-washed", "Cold storage available"],
  },
  {
    id: "spinach",
    name: "Spinach",
    category: "Fresh Produce",
    unit: "Crate (20kg)",
    pricePerUnit: 16,
    moq: 20,
    origin: "Kalobeyei Irrigation Cluster",
    grade: "Fresh A",
    lead: "24–48 hrs",
    blurb: "Nutrient-rich spinach from irrigated production zones with cold-chain preservation.",
    spec: ["Cold chain 2–6°C", "Field-washed", "Vented crates", "Daily harvest"],
  },
  {
    id: "okra",
    name: "Okra",
    category: "Fresh Produce",
    unit: "Crate (15kg)",
    pricePerUnit: 18,
    moq: 15,
    origin: "Napusimoru Riverine Farms",
    grade: "Fresh A",
    lead: "24–48 hrs",
    blurb: "Premium okra with consistent sizing, harvested fresh and cold-chain processed.",
    spec: ["Uniform sizing", "Cold chain 8–12°C", "Ventilated crates", "Same-day dispatch"],
  },
  {
    id: "wheat-flour",
    name: "Wheat Flour",
    category: "Cereals",
    unit: "Bag (50kg)",
    pricePerUnit: 55,
    moq: 20,
    origin: "Turkana Grain Mills",
    grade: "Grade 1",
    lead: "5–7 days",
    blurb: "Milled wheat flour, ready for baking and institutional food preparation.",
    spec: ["Protein ≥ 11%", "Moisture ≤ 13%", "50kg bags", "Fortified"],
  },
  {
    id: "rice",
    name: "Rice",
    category: "Cereals",
    unit: "Bag (50kg)",
    pricePerUnit: 75,
    moq: 10,
    origin: "Regional Supply Partners",
    grade: "Grade 1",
    lead: "7–10 days",
    blurb: "High-quality milled rice suitable for institutional catering and retail distribution.",
    spec: ["White rice", "Moisture ≤ 14%", "50kg bags", "Clean grain"],
  },
  {
    id: "cooking-oil",
    name: "Cooking Oil",
    category: "Oilseeds",
    unit: "Liter",
    pricePerUnit: 1.5,
    moq: 1000,
    origin: "Local Processing",
    grade: "Food Grade",
    lead: "3–5 days",
    blurb: "Refined cooking oil suitable for domestic and commercial food preparation.",
    spec: ["Food grade", "Refined", "Various volumes", "Traceable sourcing"],
  },
  {
    id: "maize",
    name: "Maize",
    category: "Cereals",
    unit: "Bag (50kg)",
    pricePerUnit: 50,
    moq: 15,
    origin: "Turkana County Farmers",
    grade: "Grade 1",
    lead: "5–7 days",
    blurb: "Dry shelled maize grain for milling, livestock feed, and food processing.",
    spec: ["Moisture ≤ 13%", "Foreign matter ≤ 1%", "50kg bags", "Fumigated"],
  },
  {
    id: "beans",
    name: "Beans",
    category: "Pulses",
    unit: "Bag (50kg)",
    pricePerUnit: 65,
    moq: 10,
    origin: "Turkana West Cooperatives",
    grade: "Grade 1",
    lead: "7–10 days",
    blurb: "Nutritious beans from sustainable farming practices across arid regions.",
    spec: ["Moisture ≤ 13%", "Purity ≥ 98%", "50kg bags", "Hand-sorted"],
  },
  {
    id: "green-peas",
    name: "Green Peas",
    category: "Pulses",
    unit: "Bag (50kg)",
    pricePerUnit: 72,
    moq: 8,
    origin: "Kalobeyei Producer Groups",
    grade: "Grade 1",
    lead: "10–14 days",
    blurb: "High-protein green peas from irrigated plots with quality grading and preservation.",
    spec: ["Moisture ≤ 12%", "Purity ≥ 99%", "50kg bags", "Machine-cleaned"],
  },
  {
    id: "eggs",
    name: "Eggs",
    category: "Specialty",
    unit: "Crate (360 eggs)",
    pricePerUnit: 85,
    moq: 5,
    origin: "Kakuma Poultry Collectives",
    grade: "Grade A",
    lead: "2–3 days",
    blurb: "Fresh eggs from managed poultry operations with daily collection and grading.",
    spec: ["Grade A", "Fresh daily", "Ventilated crates", "Cold storage ready"],
  },
  {
    id: "solar-panels",
    name: "Solar Panels",
    category: "Machinery",
    unit: "Unit",
    pricePerUnit: 1200,
    moq: 1,
    origin: "AgriLink Equipment Supply",
    grade: "Standard",
    lead: "14–21 days",
    blurb: "High-efficiency solar panels for agricultural cold storage and equipment power.",
    spec: ["High efficiency", "Durable frame", "Weather-resistant", "Technical support"],
  },
  {
    id: "drip-irrigation",
    name: "Drip Irrigation Kits",
    category: "Machinery",
    unit: "Kit (1 hectare)",
    pricePerUnit: 350,
    moq: 1,
    origin: "AgriLink Equipment Supply",
    grade: "Standard",
    lead: "7–14 days",
    blurb: "Complete drip irrigation kits for precision watering and water conservation.",
    spec: ["Complete setup", "Water-efficient", "Easy installation", "Training included"],
  },
  {
    id: "hand-pumps",
    name: "Hand Operator Pumps",
    category: "Machinery",
    unit: "Unit",
    pricePerUnit: 280,
    moq: 1,
    origin: "AgriLink Equipment Supply",
    grade: "Standard",
    lead: "5–7 days",
    blurb: "Durable hand-operated pumps for reliable water extraction in remote areas.",
    spec: ["Durable construction", "Easy maintenance", "High capacity", "Reliable"],
  },
  {
    id: "tractors",
    name: "Tractors",
    category: "Machinery",
    unit: "Unit",
    pricePerUnit: 35000,
    moq: 1,
    origin: "AgriLink Equipment Partners",
    grade: "Standard",
    lead: "30–45 days",
    blurb: "Reliable tractors for medium-scale agricultural operations and land preparation.",
    spec: ["Various sizes", "Low maintenance", "Spare parts available", "Operator training"],
  },
  {
    id: "solar-sprayers",
    name: "Solar-Powered Backpack Sprayers",
    category: "Machinery",
    unit: "Unit",
    pricePerUnit: 420,
    moq: 1,
    origin: "AgriLink Equipment Supply",
    grade: "Standard",
    lead: "10–14 days",
    blurb: "Eco-friendly solar-powered sprayers for pesticide and nutrient application.",
    spec: ["Solar-powered", "Efficient spray", "Ergonomic design", "Long battery"],
  },
  {
    id: "smartphones-tablets",
    name: "Affordable Smartphones & Tablets",
    category: "Machinery",
    unit: "Unit",
    pricePerUnit: 180,
    moq: 5,
    origin: "AgriLink Technology Partners",
    grade: "Standard",
    lead: "7–14 days",
    blurb: "Rugged smartphones and tablets for farm data collection and market access.",
    spec: ["Android OS", "Durable", "Affordable", "Bundled with apps"],
  },
];

// Extract unique categories safely
export const CATEGORIES: string[] = [
  "All",
  ...Array.from(new Set(PRODUCTS.map((p) => p.category))),
];

// Robust product lookup function
export function findProduct(id?: string): Product | undefined {
  if (!id) return undefined;
  const cleanId = id.trim().toLowerCase();
  return PRODUCTS.find((p) => p.id.toLowerCase() === cleanId);
}